export const en = {
    common: {
        save: "Save",
        cancel: "Cancel",
        confirm: "Confirm",
        close: "Close",
        back: "Back",
        edit: "Edit",
        delete: "Delete",
        yes: "Yes",
        no: "No",
        done: "Done",
        loading: "Loading...",
        error: "Error",
        success: "Success",
    },

    navigation: {
        home: "Home",
        payments: "Payments",
        members: "Members",
        history: "History",
        settings: "Settings",
        reports: "Reports",
        export: "Export",
    },

    status: {
        paid: "Paid",
        pending: "Pending",
        overdue: "Overdue",
        partiallyPaid: "Partially Paid",
        active: "Active",
        inactive: "Inactive",
    },

    members: {
        members: "Members",
        addMember: "Add Member",
        editMember: "Edit Member",
        name: "Name",
        mobile: "Mobile",
        monthlyInstallment: "Monthly Installment",
        activeMembers: "Active Members",
        inactiveMembers: "Inactive Members",
        noMembers: "No members found.",
    },

    payments: {
        payments: "Payments",
        monthlyPayments: "Monthly Payments",
        originalInstallment: "Original Installment",
        penalty: "Penalty",
        collected: "Collected",
        pending: "Pending",
        totalDue: "Total Due",
        paymentDate: "Payment Date",
        paymentTime: "Payment Time",
    },

    settings: {
        settings: "Settings",
        mandalInformation: "Mandal Information",
        changePin: "Change PIN",
        biometricUnlock: "Biometric Unlock",
        recoveryEmail: "Recovery Email",
        language: "Language",
        appLanguage: "App Language",
        notifications: "Notifications",
        reminderSettings: "Reminder Settings",
        data: "Data",
        exportData: "Export Data",
        restoreData: "Restore Data",
        about: "About",
        aboutMyMandal: "About My Mandal",
        english: "English",
        gujarati: "Gujarati",
    },

    home: {
        members: "Members",
        paid: "Paid",
        pending: "Pending",
        originalInstallments: "Original Installments",
        penalty: "Penalty",
        collected: "Collected",
        oldOverdue: "Old Overdue",
        recordPayment: "Record Payment",
        addMember: "Add Member",
        thisMonth: "This Month",
        outstandingFromPrevious: "Outstanding from previous",
        months: "months",
        quickActions: "Quick Actions",
        manage: "Manage",
    },

    history: {
        history: "History",
        yearlyHistory: "Yearly History",
        monthlyHistory: "Monthly History",
    },

    reports: {
        reports: "Reports",
        monthlyReport: "Monthly Report",
        yearlyReport: "Yearly Report",
        totalCollected: "Total Collected",
        totalInstallments: "Total Installments",
        totalPenalties: "Total Penalties",
    },
} as const;