export const gu = {
    common: {
        save: "સાચવો",
        cancel: "રદ કરો",
        confirm: "પુષ્ટિ કરો",
        close: "બંધ કરો",
        back: "પાછળ",
        edit: "ફેરફાર કરો",
        delete: "કાઢી નાખો",
        yes: "હા",
        no: "ના",
        done: "પૂર્ણ",
        loading: "લોડ થઈ રહ્યું છે...",
        error: "ભૂલ",
        success: "સફળતા",
    },

    navigation: {
        home: "હોમ",
        payments: "ચુકવણી",
        members: "સભ્યો",
        history: "ઇતિહાસ",
        settings: "સેટિંગ્સ",
        reports: "રિપોર્ટ્સ",
        export: "એક્સપોર્ટ",
    },

    status: {
        paid: "ચૂકવેલ",
        pending: "બાકી",
        overdue: "મુદત વીતી ગઈ",
        partiallyPaid: "આંશિક ચૂકવેલ",
        active: "સક્રિય",
        inactive: "નિષ્ક્રિય",
    },

    members: {
        members: "સભ્યો",
        addMember: "સભ્ય ઉમેરો",
        editMember: "સભ્યમાં ફેરફાર કરો",
        name: "નામ",
        mobile: "મોબાઇલ",
        monthlyInstallment: "માસિક હપ્તો",
        activeMembers: "સક્રિય સભ્યો",
        inactiveMembers: "નિષ્ક્રિય સભ્યો",
        noMembers: "કોઈ સભ્ય મળ્યો નથી.",
    },

    payments: {
        payments: "ચુકવણી",
        monthlyPayments: "માસિક ચુકવણી",
        originalInstallment: "મૂળ હપ્તો",
        penalty: "દંડ",
        collected: "વસૂલ કરેલ",
        pending: "બાકી",
        totalDue: "કુલ બાકી",
        paymentDate: "ચુકવણી તારીખ",
        paymentTime: "ચુકવણી સમય",
    },

    settings: {
        settings: "સેટિંગ્સ",
        mandalInformation: "મંડળની માહિતી",
        changePin: "PIN બદલો",
        biometricUnlock: "બાયોમેટ્રિક અનલોક",
        recoveryEmail: "રિકવરી ઈમેલ",
        language: "ભાષા",
        appLanguage: "એપ ભાષા",
        notifications: "નોટિફિકેશન",
        reminderSettings: "રિમાઇન્ડર સેટિંગ્સ",
        data: "ડેટા",
        exportData: "ડેટા એક્સપોર્ટ",
        restoreData: "ડેટા રિસ્ટોર",
        about: "વિશે",
        aboutMyMandal: "મારા મંડળ વિશે",
        english: "અંગ્રેજી",
        gujarati: "ગુજરાતી",
    },

    home: {
        members: "સભ્યો",
        paid: "ચૂકવેલ",
        pending: "બાકી",
        originalInstallments: "મૂળ હપ્તા",
        penalty: "દંડ",
        collected: "વસૂલ કરેલ",
        oldOverdue: "જૂનું બાકી",
        recordPayment: "ચુકવણી નોંધો",
        addMember: "સભ્ય ઉમેરો",
        thisMonth: "આ મહિનો",
        outstandingFromPrevious: "અગાઉના મહિનાની બાકી રકમ",
        months: "મહિના",
        quickActions: "ઝડપી કાર્યો",
        manage: "વ્યવસ્થાપન",
    },

    history: {
        history: "ઇતિહાસ",
        yearlyHistory: "વાર્ષિક ઇતિહાસ",
        monthlyHistory: "માસિક ઇતિહાસ",
    },

    reports: {
        reports: "રિપોર્ટ્સ",
        monthlyReport: "માસિક રિપોર્ટ",
        yearlyReport: "વાર્ષિક રિપોર્ટ",
        totalCollected: "કુલ વસૂલાત",
        totalInstallments: "કુલ હપ્તા",
        totalPenalties: "કુલ દંડ",
    },
} as const;